### ISSUE TITLE
Different spelling of license/licence

### ISSUE THREAD

**Issue by MaikHerrmann** [chxj1992/jetbrains-license-server-docker#1]
Hi chxj1992,

thanks for the good work. I was just trying your docker image, which is great. After trying to run the container several times without luck, I realized that there are different spellings of license/licence, which makes it impossible to start the container according to the README.md. Should I create a pull request to fix the different spellings or do you want to do it?

Thanks,
Maik.

**Comment by chxj1992** [comment]
Ah! I'm happy to apply a pull request. And thanks for your feedback 👻👻👻
